services:
  api:
    build:
      context: .
      target: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - db
    command: sh -c "while ! pg_isready -h db -U jemal; do echo 'Waiting for DB...'; sleep 2; done && npx prisma generate && npm run seed && npm run dev"

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: jemal
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
